apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trading-service-k6test
  name: trading-service-k6test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-service-k6test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trading-service-k6test
    spec:
      containers:
      - image: ghcr.io/monodot/trading-service-k6test:latest
        name: k6
        env:
        - name: TRADING_SERVICE_BASE_URL
          value: http://trading-service:8080
        - name: K6_DURATION
          value: 30s
        - name: K6_VUS
          value: "3"
        ports:
        - containerPort: 8080
