# This deployment assumes that you've already deployed a metrics
# collector to the cluster, like Prometheus or Grafana Agent.
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trading-service
  name: trading-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trading-service
    spec:
      containers:
      - image: ghcr.io/monodot/trading-service:latest
        name: trading-service
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: trading-service
  name: trading-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: trading-service
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
